#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
console_title_template = '{{ .UserName }}@{{ .HostName }} {{ .Shell }} in {{ .PWD }}'
final_space = true
auto_upgrade = false
shell_integration = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground_templates = [ '{{ if .Root -}} red {{- else -}} magenta {{- end }}' ]
    templates = [
      '{{ if .Root }}<b>{{ end }} {{- .UserName -}} {{ if .Root }}</b>{{ end }}',
      '{{ if .SSHSession -}} <white>@</><green>{{ .HostName }}</> {{- end }}',
    ]

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    template = " {{ .Path }}{{ if not .Writable }} <yellow></>{{ end }} "

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 2

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'cyan'
    templates = [
      '<b>{{ .HEAD }}</b>',
      '{{ if or .Working.Changed .Staging.Changed -}} <b><yellow>*</></b> {{- end }}',
      "{{ if .StashCount }} <b>≡</b>{{ end }}",
      '{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}',
    ]

    [blocks.segments.properties]
      fetch_status = true
      fetch_bare_info = true
      branch_icon = ''
      branch_identical_icon = ''
      branch_gone_icon = ''
      branch_ahead_icon = "<lightCyan><b></b></>"
      branch_behind_icon = "<lightCyan><b></b></>"

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = "yellow"
    template = "󱎫 {{ .FormattedMs }} "

    [blocks.segments.properties]
      style = 'austin'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      status_template = '{{ if .Code }}<red>{{ else }}<green>{{ end }}{{ reason .Code }}</>'
      status_separator = ' | '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

    [[blocks.segments]]
      type = 'text'
      style = 'plain'
      foreground_templates = [
        '{{ if .Code }}red{{end}}',
        'green',
      ]
      template = "❯"

[transient_prompt]
  foreground = 'green'
  template = "{{ if .Root }}<yellow></> {{end}}❯ "
