[language-server.nixd.config.nixd]
nixpkgs = { expr = "import (builtins.getFlake (toString ./.)).inputs.nixpkgs {}" }

[language-server.nixd.config.nixd.options]
nixos = { expr = "{}" }
flake-parts = { expr = "(builtins.getFlake (toString ./.)).debug.options" }
