[language-server.nixd.config.nixd]
nixpkgs = { expr = "import (builtins.getFlake (toString ./.)).inputs.nixpkgs {}" }

[language-server.nixd.config.nixd.options]
nixos = { expr = "{}" }
unora = { expr = "(builtins.getFlake (toString ./.)).nixosConfigurations.unora.options" }
unora-player = { expr = """
  let
    hm-users = (builtins.getFlake (toString ./.)).nixosConfigurations.unora.options.home-manager.users;
    user-modules = map (def: def.player131007 or {}) hm-users.definitions;
    hm-submodule = hm-users.type.nestedTypes.elemType;

    final-module = hm-submodule.substSubModules (hm-submodule.getSubModules ++ user-modules);
  in final-module.getSubOptions []
""" }
tahari = { expr = "(builtins.getFlake (toString ./.)).nixosConfigurations.tahari.options" }
flake-parts = { expr = "(builtins.getFlake (toString ./.)).debug.options" }
