[language-server.nixd.config.nixd]
nixpkgs = { expr = "import (builtins.getFlake (builtins.toString ./.)).inputs.nixpkgs {}" }

[language-server.nixd.config.nixd.options]
nixos = { expr = "(builtins.getFlake (builtins.toString ./.)).nixosConfigurations.laptop.options" }
home-manager = { expr = "(builtins.getFlake (builtins.toString ./.)).homeConfigurations.\"player131007@laptop\".options" }
