command_timeout = 5000

format = """
$username[](fg:pl1 bg:pl2)\
$hostname[](pl2)\
(\b[ ](fg:pl2 bg:pl3)$nix_shell[](fg:pl3))
[󱞩 ](bold)$directory[](pl4)\
(\b[ ](fg:pl4 bg:pl5)$git_branch$git_status[](pl5)) \
"""

right_format = """
[](pl6)$status([](fg:pl7 bg:pl6)$cmd_duration)
"""

palette = "powerline"
[palettes.powerline]
pl1 = "#3A3652"
pl2 = "#635D8C"
pl3 = "#533E8C"
pl4 = "#3D3859"
pl5 = "#2D3473"
pl6 = "#3C3B47"
pl7 = "#F5A638"

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'
style = 'purple bg:pl5'

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
conflicted = '≠'
deleted = ''
style = 'bold red bg:pl5'

[nix_shell]
format = '❄️'
style = "bg:pl3"

[status]
disabled = false
pipestatus = true
pipestatus_separator = '[|](bg:pl6)'
pipestatus_format = """
[ \\[](bg:pl6)$pipestatus[\\] =>](bg:pl6)\
[ ](bg:pl6)$symbol\
[$maybe_int](red bg:pl6)\
[$common_meaning(SIG$signal_name) ](bold red bg:pl6)\
"""
format = """
[ ](bg:pl6)$symbol\
[$maybe_int](red bg:pl6)\
[$common_meaning(SIG$signal_name) ](bold red bg:pl6)\
"""
symbol = ''
success_symbol = '[󰄬](bold fg:#00DD00 bg:pl6)'

[cmd_duration]
min_time = 1000
format = "[ 󱦟]($style bold)[ $duration ]($style)"
style = 'bg:pl7 fg:black'

[directory]
format = '[ $path ]($style)([$read_only ]($style))'
# fish_style_pwd_dir_length = 1
truncation_length = 4
truncation_symbol = '⋅⋅⋅/'
style = 'bg:pl4'

[username]
show_always = true
format = '[ $user ]($style bg:pl1)'
style_user = 'white'
style_root = 'bright-red'

[hostname]
ssh_only = false
trim_at = ''
format = "[ ($ssh_symbol )$hostname ](fg:#F5C6C4 bg:pl2)"
