# generated by wallust

from itertools import product

c.colors.completion.category.bg = "qlineargradient(x1:0, y1:-1, x2:0, y2:1.5, stop:0 {{ background }}, stop:1 {{ background | blend(color4) }})"
c.colors.completion.category.fg = "{{ foreground }}"
c.colors.completion.category.border.top = "{{ background }}"
c.colors.completion.category.border.bottom = "{{ background }}"

c.colors.completion.fg = "{{ foreground }}"
c.colors.completion.even.bg = "{{ background | lighten(0.15) }}"
c.colors.completion.odd.bg = "{{ background | lighten(0.2) }}"

c.colors.completion.item.selected.bg = "{{ color4 }}"
c.colors.completion.item.selected.border.bottom = "#00000000"
c.colors.completion.item.selected.border.top = "#00000000"
c.colors.completion.item.selected.fg = "{{ foreground }}"

c.colors.completion.item.selected.match.fg = "{{ color1 }}"
c.colors.completion.match.fg = "{{ color9 }}"

c.colors.completion.scrollbar.bg = "{{ background | lighten(0.1) }}"
c.colors.completion.scrollbar.fg = "{{ color8 }}"

c.colors.contextmenu.disabled.bg = "{{ background | lighten(0.2) }}"
c.colors.contextmenu.disabled.fg = "{{ color8 }}"
c.colors.contextmenu.menu.bg = "{{ background | lighten(0.2) }}"
c.colors.contextmenu.menu.fg = "{{ foreground }}"
c.colors.contextmenu.selected.bg = "{{ cursor | darken(0.3) }}"
c.colors.contextmenu.selected.fg = "{{ foreground }}"

c.colors.downloads.bar.bg = "{{ background }}"
c.colors.downloads.error.bg = "{{ color1 }}"
c.colors.downloads.error.fg = "{{ foreground }}"
c.colors.downloads.start.bg = "{{ color4 }}"
c.colors.downloads.start.fg = "{{ foreground }}"
c.colors.downloads.stop.bg = "{{ color2 }}"
c.colors.downloads.stop.fg = "{{ foreground }}"
c.colors.downloads.system.bg = "hsl"
c.colors.downloads.system.fg = "none"

c.colors.hints.bg = "qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba({{ color11 | rgb }}, 90%), stop:1 rgba({{ color11 | darken(0.4) | rgb }}, 90%))"
c.colors.hints.fg = "{{ foreground }}"
c.colors.hints.match.fg = "{{ color12 }}"
c.hints.border = "1px outset {{ color11 }}"

c.colors.keyhint.bg = "rgba({{ background | rgb }}, 80%)"
c.colors.keyhint.fg = "{{ foreground }}"
c.colors.keyhint.suffix.fg = "{{ color12 }}"

c.colors.messages.error.bg = "{{ color1 }}"
c.colors.messages.error.border = "{{ color9  }}"
c.colors.messages.error.fg = "{{ foreground }}"

c.colors.messages.info.bg = "{{ color4 }}"
c.colors.messages.info.border = "{{ color12 }}"
c.colors.messages.info.fg = "{{ foreground }}"

c.colors.messages.warning.bg = "{{ color3 }}"
c.colors.messages.warning.border = "{{ color11 }}"
c.colors.messages.warning.fg = "{{ foreground }}"

c.colors.prompts.bg = "{{ background | lighten(0.3) }}"
c.colors.prompts.border = "1px solid {{ background | lighten(0.2) }}"
c.colors.prompts.fg = "{{ foreground }}"
c.colors.prompts.selected.bg = "{{ background | lighten(0.5) }}"
c.colors.prompts.selected.fg = "{{ foreground }}"

c.colors.statusbar.caret.bg = "{{ color5 }}"
c.colors.statusbar.caret.fg = "{{ foreground }}"
c.colors.statusbar.caret.selection.bg = "{{ color5 | blend(color4) }}"
c.colors.statusbar.caret.selection.fg = "{{ foreground }}"

c.colors.statusbar.command.bg = "{{ background | lighten(0.1) }}"
c.colors.statusbar.command.fg = "{{ foreground }}"

c.colors.statusbar.command.private.bg = "{{ background | lighten(0.1) | blend(color6) }}"
c.colors.statusbar.command.private.fg = "{{ foreground }}"

c.colors.statusbar.insert.bg = "{{ color2 }}"
c.colors.statusbar.insert.fg = "{{ foreground }}"

c.colors.statusbar.normal.bg = "{{ background | lighten(0.1) }}"
c.colors.statusbar.normal.fg = "{{ foreground }}"

c.colors.statusbar.passthrough.bg = "{{ color4 }}"
c.colors.statusbar.passthrough.fg = "{{ foreground }}"

c.colors.statusbar.private.bg = "{{ background | lighten(0.1) | blend(color6) }}"
c.colors.statusbar.private.fg = "{{ foreground }}"

c.colors.statusbar.progress.bg = "{{ color2 }}"

c.colors.statusbar.url.error.fg = "{{ color9 }}"

c.colors.statusbar.url.fg = "{{ foreground }}"

c.colors.statusbar.url.hover.fg = "{{ color14 }}"

c.colors.statusbar.url.success.http.fg = "{{ color9 | blend(foreground) }}"
c.colors.statusbar.url.success.https.fg = "{{ foreground }}"

c.colors.statusbar.url.warn.fg = "{{ color11 }}"

c.colors.tabs.bar.bg = "#00000000"
c.colors.tabs.indicator.error = "{{ color9 }}"
c.colors.tabs.indicator.start = "{{ color11 }}"
c.colors.tabs.indicator.stop = "{{ color10 }}"
c.colors.tabs.indicator.system = "none"

TAB_COLORS = {
    'bg': "rgba({{ background | lighten(0.1) | rgb }}, 60%)",
    'fg': "{{ foreground }}"
}

TAB_SELECTED_COLORS = {
    'bg': "rgba({{ color4 | rgb }}, 60%)",
    'fg': "{{ foreground }}"
}

for position, color, pinned in product(('odd', 'even'), ('bg', 'fg'), ('', '.pinned')):
    config.set(f'colors.tabs{pinned}.selected.{position}.{color}', TAB_SELECTED_COLORS[color])
    config.set(f'colors.tabs{pinned}.{position}.{color}', TAB_COLORS[color])

c.colors.tooltip.bg = "{{ background | lighten(0.2) }}"
c.colors.tooltip.fg = "{{ foreground }}"

c.colors.webpage.bg = "{{ background }}"
